"""
GitHub / TFS Push Utility — Creates feature branches and raises PRs
for bug fixes generated by the CSFMD Bug Agent.

Supports two modes:
  1. Push fix files to the CSF Web Client UI Automation GitHub repo
  2. Push source fixes to the OnBase TFS repo (via tf.exe)

Requires:
  GIT_TOKEN  – GitHub Personal Access Token with repo scope
  OR the user is already authenticated via `gh auth` / git credential manager
"""


import os
import subprocess
import sys
from pathlib import Path
from datetime import datetime

REPO_DIR = Path(os.environ.get(
    "CSF_REPO_DIR",
    os.path.expanduser("~/source/repos/CSF-ob-client-web-ui-automation-master"),
))
REMOTE_URL = "https://github.com/HylandFoundation/CSF-ob-client-web-ui-automation.git"
AGENT_TEST_DIR = "Hyland.Applications.Web.Client.Agent.Test"
GIT_USER_NAME = "Tamisra Sarkar"
GIT_USER_EMAIL = "tamisra.sarkar@hyland.com"


def _run(cmd: list[str], cwd: Path = REPO_DIR, check: bool = True) -> subprocess.CompletedProcess:
    """Run a subprocess command in the repo directory."""
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"  STDERR: {result.stderr.strip()}")
        raise RuntimeError(f"Command failed: {' '.join(cmd)}")
    return result


def ensure_repo_ready():
    """Ensure the local repo exists and is configured."""
    if not REPO_DIR.exists():
        print(f"ERROR: Repo directory not found: {REPO_DIR}")
        print("  Set CSF_REPO_DIR env var or clone the repo first.")
        sys.exit(1)

    # Configure git user
    _run(["git", "config", "user.name", GIT_USER_NAME])
    _run(["git", "config", "user.email", GIT_USER_EMAIL])

    # Ensure remote points to the right place (add upstream if needed)
    result = _run(["git", "remote", "-v"], check=False)
    if "HylandFoundation" not in result.stdout:
        # Check if upstream exists
        if "upstream" in result.stdout:
            _run(["git", "remote", "set-url", "upstream", REMOTE_URL])
        else:
            _run(["git", "remote", "add", "upstream", REMOTE_URL])
        print(f"  ✓ Upstream remote configured: {REMOTE_URL}")


def create_branch(jira_ids: list[str]) -> str:
    """Create a feature branch for the generated tests."""
    # Build branch name from JIRA IDs
    ids_slug = "-".join(jid.replace("CSFMD-", "") for jid in jira_ids[:5])
    timestamp = datetime.now().strftime("%Y%m%d")
    branch_name = f"feature/tamisra.sarkar/agent-tests-{ids_slug}-{timestamp}"

    # Fetch latest from main/master
    _run(["git", "fetch", "origin"], check=False)

    # Determine default branch
    result = _run(["git", "symbolic-ref", "refs/remotes/origin/HEAD"], check=False)
    if result.returncode == 0:
        default_branch = result.stdout.strip().split("/")[-1]
    else:
        default_branch = "main"

    # Create branch from latest
    _run(["git", "checkout", default_branch], check=False)
    _run(["git", "pull", "origin", default_branch], check=False)
    _run(["git", "checkout", "-b", branch_name], check=False)

    print(f"  ✓ Created branch: {branch_name}")
    return branch_name


def copy_test_files(generated_files: list[Path]) -> list[Path]:
    """Copy generated test files into the Agent.Test project directory."""
    dest_dir = REPO_DIR / AGENT_TEST_DIR
    dest_dir.mkdir(parents=True, exist_ok=True)

    copied = []
    for src in generated_files:
        dest = dest_dir / src.name
        dest.write_text(src.read_text(encoding="utf-8-sig"), encoding="utf-8-sig")
        copied.append(dest)
        print(f"  ✓ Copied {src.name} → {AGENT_TEST_DIR}/")
    return copied


def update_csproj(file_names: list[str]):
    """Add new test files to the .csproj <Compile> ItemGroup."""
    csproj_path = REPO_DIR / AGENT_TEST_DIR / f"{AGENT_TEST_DIR}.csproj"
    if not csproj_path.exists():
        print(f"  ⚠ .csproj not found at {csproj_path}; skipping update")
        return

    content = csproj_path.read_text(encoding="utf-8")

    # Check which files are already included
    new_entries = []
    for fname in file_names:
        if fname not in content:
            new_entries.append(f'    <Compile Include="{fname}" />')

    if not new_entries:
        print("  ✓ All files already in .csproj")
        return

    # Insert before the closing </ItemGroup> that contains other <Compile> entries
    import re
    # Find the ItemGroup containing Compile entries
    pattern = r"(<Compile Include=\"LoginTests\.cs\"[^/]*/>\s*)"
    match = re.search(pattern, content)
    if match:
        insert_point = match.end()
        insert_text = "\n" + "\n".join(new_entries)
        content = content[:insert_point] + insert_text + content[insert_point:]
    else:
        # Fallback: insert before last </ItemGroup>
        last_ig = content.rfind("</ItemGroup>")
        if last_ig != -1:
            insert_text = "\n".join(new_entries) + "\n  "
            content = content[:last_ig] + insert_text + content[last_ig:]

    csproj_path.write_text(content, encoding="utf-8")
    print(f"  ✓ Added {len(new_entries)} entries to .csproj")


def commit_and_push(branch_name: str, jira_ids: list[str]) -> str:
    """Stage, commit, and push changes."""
    _run(["git", "add", "-A"])

    ids_str = ", ".join(jira_ids)
    commit_msg = f"feat: add agent-generated tests for {ids_str}"
    _run(["git", "commit", "-m", commit_msg])

    _run(["git", "push", "origin", branch_name])

    print(f"\n  ✓ Pushed to origin/{branch_name}")
    print(f"  → Create PR at: https://github.com/HylandFoundation/CSF-ob-client-web-ui-automation/compare/{branch_name}")
    return branch_name


def push_generated_tests(generated_files: list[Path], jira_ids: list[str]) -> str:
    """Full workflow: branch → copy → update csproj → commit → push."""
    print("\n[GitHub Push]")

    ensure_repo_ready()
    branch = create_branch(jira_ids)
    copied = copy_test_files(generated_files)
    update_csproj([f.name for f in copied])
    commit_and_push(branch, jira_ids)

    return branch


def push_bug_fixes(bug_key: str, fix_files: list[Path], description: str = "") -> str:
    """Push bug fix files to a feature branch and return the branch name.

    Args:
        bug_key: JIRA bug key (e.g. CSFMD-10288)
        fix_files: List of fix file paths to commit
        description: Commit message description
    Returns:
        Branch name
    """
    print(f"\n[Push Bug Fix: {bug_key}]")

    ensure_repo_ready()
    branch = create_branch([bug_key])

    dest_dir = REPO_DIR / "fixes" / bug_key
    dest_dir.mkdir(parents=True, exist_ok=True)

    for src in fix_files:
        dest = dest_dir / src.name
        dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"  ✓ Copied {src.name} → fixes/{bug_key}/")

    _run(["git", "add", "-A"])

    msg = f"fix({bug_key}): {description or 'Agent-generated bug fix'}"
    _run(["git", "commit", "-m", msg])
    _run(["git", "push", "origin", branch])

    print(f"\n  ✓ Pushed fix to origin/{branch}")
    pr_url = f"https://github.com/HylandFoundation/CSF-ob-client-web-ui-automation/compare/{branch}"
    print(f"  → Create PR: {pr_url}")

    return branch


def create_pull_request(branch_name: str, title: str, body: str) -> str:
    """Create a GitHub PR using the `gh` CLI. Returns the PR URL."""
    result = _run(
        ["gh", "pr", "create",
         "--base", "main",
         "--head", branch_name,
         "--title", title,
         "--body", body],
        check=False,
    )
    if result.returncode == 0:
        pr_url = result.stdout.strip()
        print(f"  ✓ PR created: {pr_url}")
        return pr_url
    else:
        print(f"  ⚠ PR creation failed: {result.stderr.strip()}")
        print(f"  → Manual PR link: https://github.com/HylandFoundation/CSF-ob-client-web-ui-automation/compare/{branch_name}")
        return ""
